# Generated by Django 5.0.1 on 2024-03-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
