# Generated by Django 5.2.3 on 2025-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Enter the discount percentage as an integer.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
