# Generated by Django 5.2.3 on 2025-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_grand_total_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
    ]
