# Generated by Django 5.2.3 on 2025-08-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_grand_total_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
    ]
