# Generated by Django 5.2.3 on 2025-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_orderitem_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='renew_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
