# Generated by Django 5.2.3 on 2025-09-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_payment_renew_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
