# Generated by Django 5.0.1 on 2024-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSpecs',
            new_name='ItemSpecValue',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='item',
            name='specs',
            field=models.ManyToManyField(through='store.ItemSpecValue', to='store.spec'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter the discount percentage as an integer.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
